name: Debug

on:
  workflow_dispatch:
    inputs:
      dumpContext:
        description: "Dump GitHub context"
        required: true
        type: boolean
        default: true
      createRelease:
        description: "Create release"
        required: true
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Setup environment variables
        run: |
          echo "REPO_NAME=`basename ${{ github.repository }}`" >> $GITHUB_ENV
          echo "LATEST_TAG=$(curl -qsSL \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "${{ github.event.repository.url }}/releases/latest" \
          | jq -r .tag_name)" >> $GITHUB_ENV
      - name: Dump GitHub context
        if: github.event.inputs.dumpContext
        run: echo "$GITHUB_CONTEXT"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: Get repository name
        id: repo-basename
        run: echo "value=`basename ${{ github.repository }}`" >> $GITHUB_OUTPUT
        shell: bash
      - name: Print repository name
        run: |
          echo "Repository name: ${{ steps.repo-basename.outputs.value }}"
      - name: Create release
        if: github.event.inputs.createRelease
        uses: actions/create-release@master
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ env.REPO_NAME }} ${{ github.ref_name }}
          body: "**Full Changelog**: ${{ github.event.repository.html_url }}/compare/${{ env.LATEST_TAG }}...${{ github.ref_name }}"
          draft: true
          prerelease: true
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: "18.x"
      - name: Run automation script
        run: cd ./.github/automation & npm start
        shell: bash
        env:
          MY_NAME: ${{ github.repository }}
