name: Publish Release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
jobs:
  publish-release:
    name: Publish Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.1.0
        with:
          myToken: ${{ env.GITHUB_TOKEN }}
          fetch: false
      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          always-auth: true
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
          scope: "@cheatoid"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Create release
        uses: actions/create-release@master
        with:
          tag_name: ${{ github.ref }}
          release_name: TS-plugins ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: ${{ contains(github.ref, '-alpha') || contains(github.ref, '-beta') }}
      - name: Publish package
        run: npm publish --access public
